USE [master]
GO

/****** Object:  Database [SignalRdb]    Script Date: 9/5/2019 10:38:25 AM ******/
CREATE DATABASE [SignalRdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SignalRdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SignalRdb.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SignalRdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\SignalRdb_log.ldf' , SIZE = 784KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SignalRdb] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SignalRdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SignalRdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SignalRdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SignalRdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SignalRdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SignalRdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [SignalRdb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SignalRdb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [SignalRdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SignalRdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SignalRdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SignalRdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SignalRdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SignalRdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SignalRdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SignalRdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SignalRdb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SignalRdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SignalRdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SignalRdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SignalRdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SignalRdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SignalRdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SignalRdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SignalRdb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SignalRdb] SET  MULTI_USER 
GO

ALTER DATABASE [SignalRdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SignalRdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SignalRdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SignalRdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SignalRdb] SET  READ_WRITE 
GO

